name: Push latest tag to docker hub

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Docker tag to set as latest

permissions:
  contents: read

env:
  DOCKER_IMAGE: bitcoindevproject/simln

jobs:
  update-docker-images-to-latest:
    name: Update docker images to latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ inputs.tag }}
          regex: v?(.+)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker tag and push latest
        run: |
          docker buildx imagetools create -t ${{ env.DOCKER_IMAGE }}:latest ${{ env.DOCKER_IMAGE }}:${{ steps.regex-match.outputs.group1 }}
